// fixtures/react-css-modules/components/App.jsx
import './styles.css';
import './styles.less';
import './styles.scss';
import './styles.stylus';
import * as stylesCss from './styles.module.css?module';
import * as stylesLess from './styles.module.less?module';
import * as stylesScss from './styles.module.scss?module';
import * as stylesStylus from './styles.module.stylus?module';

export default function App() {
    return <div className={`red large justified lowercase ${stylesCss.italic} ${stylesLess.underline} ${stylesScss.bold} ${stylesStylus.rtl}`}></div>
}

// fixtures/vuejs-css-modules/App.vue
<template>
  <div id="app" class="red large justified lowercase" :class="[$css.italic, $scss.bold, $less.underline, $stylus.rtl]"></div>
</template>

<style>
  .red {
    color: red;
  }
</style>

<style lang="scss">
  .large {
    font-size: 50px;
  }
</style>

<style lang="less">
  .justified {
    text-align: justify;
  }
</style>

<style lang="styl">
  .lowercase
    text-transform: lowercase
</style>

<style module="$css">
  .italic {
    font-style: italic;
  }
</style>

<style lang="scss" module="$scss">
  .bold {
    font-weight: bold;
  }
</style>

<style lang="less" module="$less">
  .underline {
    text-decoration: underline;
  }
</style>

<style lang="styl" module="$stylus">
  .rtl
    direction: rtl;
</style>
